import RLSystemParam from "./RLSystemParam";

export default function isConstraint(p: RLSystemParam) {
  return [
    "Appearance",
    "OldPosition",
    "Position",
    "MoveAction",
    "MeleeAction",
    "Actor",
    "Fighter",
    "Consumable",
    "Inventory",
    "InventoryActionConfig",
    "TargetingActionConfig",
    "TargetingItemConfig",
    "ConfusedEnemy",
    "Progress",
    "IsBlocker",
    "IsPlayer",
    "RecalculateFOV",
    "RedrawMe",
    "RedrawUI",
    "MyTurn",
    "HostileEnemy",
    "WaitAction",
    "HistoryAction",
    "Item",
    "PickupAction",
    "InventoryAction",
    "DropAction",
    "LookAction",
    "QuitAction",
    "TakeStairsAction",
    "GainingLevel",
    "CharacterInfoAction",
  ].includes(p.typeName);
}
